apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: customerapi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: customerapi
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: customerapi
        image: akscontdemoacr.azurecr.io/customerapi:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: customerapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: customerapi
